target-version = "py39"
exclude = [".venv", "tests"]

[lint]
select = ["E","F","B","I","UP","SIM","S","ANN"]

[format]
line-ending = "lf"
quote-style = "single"
indent-style = "space"

[lint.flake8-quotes]
docstring-quotes = "double"