# Dunno why, but i had to add this to make building it from the command line work
[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"

# Just for me
[build]
target = "x86_64-unknown-linux-gnu"